### ISSUE TITLE
Add the ability to post drip pics

### ISSUE THREAD

**Issue by shatindle** [shatindle/rsplatoon-profile#1]
Shane — Today at 8:33 PM
just for my own curiosity, what would you want in profile next?
Leslie — Today at 8:34 PM
Inserting pics
Kellie — Today at 8:34 PM
drip pics
Leslie — Today at 8:34 PM
Check my non existent drip
Shane — Today at 8:34 PM
so like a profile pic?
Leslie — Today at 8:34 PM
Yeah
Shane — Today at 8:34 PM
I'd need to figure out a way to store it
I suppose I could do it via link
Nautalyst — Today at 8:35 PM
Uploads to imgur?
Shane — Today at 8:35 PM
is that a thing that can be done programmatically easily?
Leslie — Today at 8:35 PM
A new challenger approaches!
Pictures and a sense of sanity
Nautalyst — Today at 8:35 PM
I fear anything I say to answer that would be woefully uninformed
Leslie — Today at 8:36 PM
Only coding experience I have is scratch
Kitty
🌱 Maltari 🌱 — Today at 8:36 PM
Profile picture = true

**Comment by Jiro-Tempest** [comment]
Oomi

**Comment by shatindle** [comment]
Drip created
